rsdns: fix `missing documentation` errors
Appeared since v1.83.0-beta.1:

error: missing documentation for an associated constant
   --> src/message/rcode.rs:109:5
    |
109 |     pub const VALUES: [RCode; 7] = [
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D missing-docs` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(missing_docs)]`

error: missing documentation for an associated constant
   --> src/records/class.rs:125:5
    |
125 |     pub const VALUES: [Class; 5] = [Self::IN, Self::CS, Self::CH, Self::HS, Self::ANY];
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: missing documentation for an associated constant
   --> src/records/type.rs:179:5
    |
179 |     pub const VALUES: [Type; 22] = [
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `rsdns` (lib test) due to 3 previous errors