github: bump the MSRV to 1.70.0
Due to an indirect dependency which fails with the following error on
1.65.0

---
error[E0658]: use of unstable library feature 'once_cell'
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.21/src/gitignore.rs:596:9
    |
596 |     use std::sync::OnceLock;
    |         ^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #74465 <https://github.com/rust-lang/rust/issues/74465> for more information