github: bump MSRV to 1.73.0
This is done due to an indirect `bstr v1.11.0` dependency needed by
`tera`:

error: package `bstr v1.11.0` cannot be built because it requires rustc 1.73 or newer, while the currently active rustc version is 1.70.0